import { renderCliCommand } from "../shared/cli-name.ts";
import {
  renderCanonicalRouteIdList,
  renderLegacyCompatibleRouteInputList,
} from "../config/route-contract.ts";

export function renderRoutesHelp() {
  return [
    renderCliCommand("routes"),
    "",
    "Usage:",
    `  ${renderCliCommand("routes --help")}`,
    `  ${renderCliCommand("routes help")}`,
    `  ${renderCliCommand("routes list [--channel <slack|telegram>] [--bot <id>] [--json]")}`,
    `  ${renderCliCommand("routes add --channel <slack|telegram> <dm:*|dm:<id>> [--bot <id>] [--policy <...>] [--require-mention <true|false>] [--allow-bots <true|false>]")}`,
    `  ${renderCliCommand("routes add --channel <slack|telegram> group:* [--bot <id>] [--policy <...>] [--require-mention <true|false>] [--allow-bots <true|false>]")}`,
    `  ${renderCliCommand("routes add --channel slack group:<id> [--bot <id>] [--policy <...>] [--require-mention <true|false>] [--allow-bots <true|false>]")}`,
    `  ${renderCliCommand("routes add --channel telegram <group:<chatId>|topic:<chatId>:<topicId>> [--bot <id>] [--policy <...>] [--require-mention <true|false>] [--allow-bots <true|false>]")}`,
    `  ${renderCliCommand("routes get --channel <slack|telegram> <route-id> [--bot <id>] [--json]")}`,
    `  ${renderCliCommand("routes enable --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes disable --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes remove --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes get-agent --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes set-agent --channel <slack|telegram> <route-id> [--bot <id>] --agent <id>")}`,
    `  ${renderCliCommand("routes clear-agent --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes get-policy --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes set-policy --channel <slack|telegram> <route-id> [--bot <id>] --policy <...>")}`,
    `  ${renderCliCommand("routes get-require-mention --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes set-require-mention --channel <slack|telegram> <route-id> [--bot <id>] --value <true|false>")}`,
    `  ${renderCliCommand("routes get-allow-bots --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes set-allow-bots --channel <slack|telegram> <route-id> [--bot <id>] --value <true|false>")}`,
    `  ${renderCliCommand("routes add-allow-user --channel <slack|telegram> <route-id> [--bot <id>] --user <principal>")}`,
    `  ${renderCliCommand("routes remove-allow-user --channel <slack|telegram> <route-id> [--bot <id>] --user <principal>")}`,
    `  ${renderCliCommand("routes add-block-user --channel <slack|telegram> <route-id> [--bot <id>] --user <principal>")}`,
    `  ${renderCliCommand("routes remove-block-user --channel <slack|telegram> <route-id> [--bot <id>] --user <principal>")}`,
    `  ${renderCliCommand("routes get-follow-up-mode --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes set-follow-up-mode --channel <slack|telegram> <route-id> [--bot <id>] --mode <auto|mention-only|paused>")}`,
    `  ${renderCliCommand("routes get-follow-up-ttl --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes set-follow-up-ttl --channel <slack|telegram> <route-id> [--bot <id>] --minutes <n>")}`,
    `  ${renderCliCommand("routes get-response-mode --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes set-response-mode --channel <slack|telegram> <route-id> [--bot <id>] --mode <capture-pane|message-tool>")}`,
    `  ${renderCliCommand("routes clear-response-mode --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes get-additional-message-mode --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes set-additional-message-mode --channel <slack|telegram> <route-id> [--bot <id>] --mode <queue|steer>")}`,
    `  ${renderCliCommand("routes clear-additional-message-mode --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes get-timezone --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    `  ${renderCliCommand("routes set-timezone --channel <slack|telegram> <route-id> [--bot <id>] <iana-timezone>")}`,
    `  ${renderCliCommand("routes clear-timezone --channel <slack|telegram> <route-id> [--bot <id>]")}`,
    "",
    "Notes:",
    `  - Canonical CLI ids are ${renderCanonicalRouteIdList()}.`,
    "  - Inside bot config, canonical stored keys are raw ids plus `*`.",
    `  - Backward-compatible input still accepts legacy ids such as ${renderLegacyCompatibleRouteInputList()}.`,
    "  - Shared group policy values are `disabled`, `allowlist`, and `open`.",
    "  - DM wildcard policy values are `disabled`, `pairing`, `allowlist`, and `open`.",
    "  - `pairing approve <channel> <code>` writes the approved sender into the requesting bot's `dm:*` allowUsers.",
    "  - `groupPolicy`/Slack `channelPolicy` control which groups are admitted; `group:*` controls the default sender policy inside admitted groups.",
    "  - With default group admission `allowlist`, adding `group:<id>` makes that group usable immediately with default sender policy `open`.",
    "  - `routes add` can set `--policy`, `--require-mention`, and `--allow-bots` in the same command.",
    "  - Use `group:*` with `add-allow-user` when one user should be allowed in every admitted group under that bot.",
    "  - `policy: disabled` means fully silent on that surface, including owner/admin and pairing guidance.",
    "  - In enabled multi-user surfaces, owner/admin bypass allowlist by default, but `blockUsers` still wins.",
    "  - If a sender is not in `allowUsers` on a multi-user route, the bot replies: `You are not allowed to use this bot in this group. Ask a bot owner or admin to add you to `allowUsers` for this surface.`",
    "  - Use `bots set-agent ...` when the whole bot should change fallback agent; use `routes set-agent ...` only when one route needs a different agent.",
    "  - Use route timezone only when one Slack/Telegram surface needs different wall-clock time from the app or agent default.",
    "  - `routes get-timezone` prints the route override, effective timezone, and current local time for that surface.",
    "",
    "Examples:",
    `  ${renderCliCommand("routes add --channel telegram group:-1001234567890 --bot alerts --require-mention false --allow-bots true --policy allowlist")}`,
    `  ${renderCliCommand("routes add-allow-user --channel slack group:* --bot default --user U_OWNER")}`,
    `  ${renderCliCommand("routes add-allow-user --channel telegram group:* --bot alerts --user 1276408333")}`,
    `  ${renderCliCommand("routes add-block-user --channel telegram group:* --bot default --user 1276408333")}`,
    `  ${renderCliCommand("routes add-allow-user --channel slack dm:* --bot support --user U123ABC456")}`,
    `  ${renderCliCommand("routes add-block-user --channel telegram dm:* --bot alerts --user 1276408333")}`,
    `  ${renderCliCommand("routes add-allow-user --channel slack group:C1234567890 --bot default --user U_OWNER")}`,
    `  ${renderCliCommand("routes add-block-user --channel telegram group:-1001234567890 --bot default --user 1276408333")}`,
    `  ${renderCliCommand("routes set-timezone --channel telegram group:-1001234567890 --bot default Asia/Ho_Chi_Minh")}`,
  ].join("\n");
}
